version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
  environment = ["nodejs"]

[[transformers]]
name = "prettier"
enabled = true